
services:
  ollama:
    image: ollama/ollama:latest
    container_name: gmail-chatbot-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    
  chatbot:
    build: .
    container_name: gmail-chatbot-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./credentials:/app/credentials
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data: